language: java
sudo: false
jdk: openjdk8
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/80c005f86406b32383e0
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - secure: UCafCVnQFrQSa+5NdwXGMBB2Wu+5d6cvhWEZNe+ttNI8ZS/kFgnocEJn6YJeLRZvgtzXnaCh9zWldUgUD7pf277gDdbur0GAk5GGybswvdN3NgeLqnxGlGR92ySFfkWX0iX9poWpudyJp/tMiAfshthazoRIFineIKUOhE1Wm3g=
  - secure: PTa8WX+RMeapLv0eIizRH0Fxvl/n3tdaOvIZ8qRyZOX2u+GJpC9Y4Z4PdGJInro0IGFlt+/TfU008Ob7qQADO+xkhq/yYCwHPWmu57zfva5ltDJqAFKxymC/YwOnOGyEqo44Ub4TTgNVwey7K72uNdiTdMzS81EJ1E/rnY8KpOE=
  - secure: VtryWtEKHOoji/QdWyAQpwKP3i7mPGlnlvJ8rWXUmQ0HcJTJy5Gc08joMvx5qkKowdBpUHVbSwSLyp4/VZc+CSPZPTFZxUdNYowqXmVUPyP2MfnQmfQSq01BUoOIHYcMEF8d9L7vKoMg5HlGEJZ84Dpl4aPsK1G2pukdUqJCLRE=
  - secure: BybG2aTAybBBdXFlxmtUnfFsDUCAE84mf2kxl4bOHoznF/n4JmRHzRFGIDEdAMYqnKssqLnmxP0znntO/Gh2rJ1cjUXr15zhT/b4msK2CKaoWOu4fcI+ZkQTo2njTmXXVoL57gfBlpXbl1dRYZ3yM5RM7AolQnugn4TezHPChxA=
  - secure: WjamMgm3iVujyQvLG+GiFuBDAVlFKnTABQy4sWhUrQa29cyyWhtROCHuPXMase1Ic57ZVFesL04bp44kipldzzuF7rsuseaH09Eolk8MbnkwiGkFHr+9Tdt7L9vsuFdAOhpnETBfc19sL2zd2bRGiz90RbqgSp6gKKtThG650CU=
  - secure: gzZYvQS6dzuc6UoPAJoswmprX0OQGLf4m52/qU5eKQJeIUB7n5KRrmHTnH9AmVvtQNoTyH85D9OL4eA7HY4Vjc8Ko0W6OfHQA/MrRJrj9VRs92pajaj5pYrCyNDkWpANkOchKLnRTOLk/ZIHmDlBmjW5+PxnovIbjPZqkPcRdKE=
